In [2]:
import numpy as np
import pandas as pd

df = pd.read_csv("food_coded.xls")


In [3]:
df.drop(111, axis=0, inplace=True)

In [4]:
df.columns

Index(['GPA', 'Gender', 'breakfast', 'calories_chicken', 'calories_day',
       'calories_scone', 'coffee', 'comfort_food', 'comfort_food_reasons',
       'comfort_food_reasons_coded', 'cook', 'comfort_food_reasons_coded.1',
       'cuisine', 'diet_current', 'diet_current_coded', 'drink',
       'eating_changes', 'eating_changes_coded', 'eating_changes_coded1',
       'eating_out', 'employment', 'ethnic_food', 'exercise',
       'father_education', 'father_profession', 'fav_cuisine',
       'fav_cuisine_coded', 'fav_food', 'food_childhood', 'fries', 'fruit_day',
       'grade_level', 'greek_food', 'healthy_feeling', 'healthy_meal',
       'ideal_diet', 'ideal_diet_coded', 'income', 'indian_food',
       'italian_food', 'life_rewarding', 'marital_status',
       'meals_dinner_friend', 'mother_education', 'mother_profession',
       'nutritional_check', 'on_off_campus', 'parents_cook', 'pay_meal_out',
       'persian_food', 'self_perception_weight', 'soup', 'sports', 'thai_food',
       

In [5]:
pd.set_option('display.max_rows',None)

In [6]:
df.isnull().sum()

GPA                              2
Gender                           0
breakfast                        0
calories_chicken                 0
calories_day                    19
calories_scone                   1
coffee                           0
comfort_food                     1
comfort_food_reasons             2
comfort_food_reasons_coded      18
cook                             3
comfort_food_reasons_coded.1     0
cuisine                         16
diet_current                     1
diet_current_coded               0
drink                            2
eating_changes                   3
eating_changes_coded             0
eating_changes_coded1            0
eating_out                       0
employment                       9
ethnic_food                      0
exercise                        13
father_education                 1
father_profession                2
fav_cuisine                      1
fav_cuisine_coded                0
fav_food                         2
food_childhood      

In [7]:
df['GPA'].unique()

array(['2.4', '3.654', '3.3', '3.2', '3.5', '2.25', '3.8', '3.904', '3.4',
       '3.6', '3.1', nan, '4', '2.2', '3.87', '3.7', '3.9', '2.8', '3',
       '3.65', '3.89', '2.9', '3.605', '3.83', '3.292', '3.35',
       'Personal ', '2.6', '3.67', '3.73', '3.79 bitch', '2.71', '3.68',
       '3.75', '3.92', 'Unknown', '3.77', '3.63', '3.882'], dtype=object)

In [8]:
# Convert to numeric 
df['GPA'] = pd.to_numeric(df['GPA'], errors='coerce')

In [9]:
df.dtypes

GPA                             float64
Gender                            int64
breakfast                         int64
calories_chicken                  int64
calories_day                    float64
calories_scone                  float64
coffee                            int64
comfort_food                     object
comfort_food_reasons             object
comfort_food_reasons_coded      float64
cook                            float64
comfort_food_reasons_coded.1      int64
cuisine                         float64
diet_current                     object
diet_current_coded                int64
drink                           float64
eating_changes                   object
eating_changes_coded              int64
eating_changes_coded1             int64
eating_out                        int64
employment                      float64
ethnic_food                       int64
exercise                        float64
father_education                float64
father_profession                object


In [10]:
# Find row where 'product' == 'apple' and change its 'price' column
row_index = df.loc[df['GPA'] == '3.79 bitch'].index   # first match
df.loc[row_index, 'price'] = 3.79

In [11]:
df['GPA'].unique()

array([2.4  , 3.654, 3.3  , 3.2  , 3.5  , 2.25 , 3.8  , 3.904, 3.4  ,
       3.6  , 3.1  ,   nan, 4.   , 2.2  , 3.87 , 3.7  , 3.9  , 2.8  ,
       3.   , 3.65 , 3.89 , 2.9  , 3.605, 3.83 , 3.292, 3.35 , 2.6  ,
       3.67 , 3.73 , 2.71 , 3.68 , 3.75 , 3.92 , 3.77 , 3.63 , 3.882])

In [12]:
mean_GPA = df['GPA'].mean() 
df['GPA'] =  df['GPA'].fillna(mean_GPA)

In [13]:
df['GPA'].unique()

array([2.4       , 3.654     , 3.3       , 3.2       , 3.5       ,
       2.25      , 3.8       , 3.904     , 3.4       , 3.6       ,
       3.1       , 3.41989076, 4.        , 2.2       , 3.87      ,
       3.7       , 3.9       , 2.8       , 3.        , 3.65      ,
       3.89      , 2.9       , 3.605     , 3.83      , 3.292     ,
       3.35      , 2.6       , 3.67      , 3.73      , 2.71      ,
       3.68      , 3.75      , 3.92      , 3.77      , 3.63      ,
       3.882     ])

In [14]:
df['calories_day'].unique()

array([nan,  3.,  4.,  2.])

In [15]:
mean_cal = df['calories_day'].mean() 
df['calories_day'] =  df['calories_day'].fillna(mean_cal)

In [16]:
df['calories_day'].unique()

array([3.03809524, 3.        , 4.        , 2.        ])

In [17]:
df.isnull().sum()

GPA                               0
Gender                            0
breakfast                         0
calories_chicken                  0
calories_day                      0
calories_scone                    1
coffee                            0
comfort_food                      1
comfort_food_reasons              2
comfort_food_reasons_coded       18
cook                              3
comfort_food_reasons_coded.1      0
cuisine                          16
diet_current                      1
diet_current_coded                0
drink                             2
eating_changes                    3
eating_changes_coded              0
eating_changes_coded1             0
eating_out                        0
employment                        9
ethnic_food                       0
exercise                         13
father_education                  1
father_profession                 2
fav_cuisine                       1
fav_cuisine_coded                 0
fav_food                    

In [18]:
df.shape

(124, 62)

In [19]:
df['calories_scone'].unique()

array([315., 420., 980.,  nan])

In [20]:
mean_cal = df['calories_scone'].mean() 
df['calories_scone'] =  df['calories_scone'].fillna(mean_cal)

In [21]:
df['calories_scone'].unique()

array([315.        , 420.        , 980.        , 501.38211382])

In [22]:
df['coffee'].unique()

array([1, 2])

In [23]:
df['comfort_food'].value_counts()

comfort_food
none                                                                                                 1
Mac and cheese, lasagna, Chinese food                                                                1
Macaroni and cheese, chicken noodle soup, pizza                                                      1
chips, ice cream, fruit snacks                                                                       1
carrots, plantain chips, almonds, popcorn                                                            1
Little Debbie snacks, donuts, pizza                                                                  1
pizza, pasta, mac and cheese                                                                         1
Chinese food, moes, sponge candy, homemade lasagne                                                   1
Ice cream, pizza, cookies                                                                            1
Pasta dishes, Cheesecake, Pancakes                          

In [24]:
mean_cal = df['comfort_food'].mode() 
df['comfort_food'] =  df['comfort_food'].fillna(mean_cal)

In [25]:
df.dtypes

GPA                             float64
Gender                            int64
breakfast                         int64
calories_chicken                  int64
calories_day                    float64
calories_scone                  float64
coffee                            int64
comfort_food                     object
comfort_food_reasons             object
comfort_food_reasons_coded      float64
cook                            float64
comfort_food_reasons_coded.1      int64
cuisine                         float64
diet_current                     object
diet_current_coded                int64
drink                           float64
eating_changes                   object
eating_changes_coded              int64
eating_changes_coded1             int64
eating_out                        int64
employment                      float64
ethnic_food                       int64
exercise                        float64
father_education                float64
father_profession                object


In [26]:
df.isnull().sum()

GPA                               0
Gender                            0
breakfast                         0
calories_chicken                  0
calories_day                      0
calories_scone                    0
coffee                            0
comfort_food                      0
comfort_food_reasons              2
comfort_food_reasons_coded       18
cook                              3
comfort_food_reasons_coded.1      0
cuisine                          16
diet_current                      1
diet_current_coded                0
drink                             2
eating_changes                    3
eating_changes_coded              0
eating_changes_coded1             0
eating_out                        0
employment                        9
ethnic_food                       0
exercise                         13
father_education                  1
father_profession                 2
fav_cuisine                       1
fav_cuisine_coded                 0
fav_food                    

In [27]:
df['comfort_food_reasons'].unique()

array(['we dont have comfort ', 'Stress, bored, anger', 'stress, sadness',
       'Boredom', 'Stress, boredom, cravings ',
       "None, i don't eat comfort food. I just eat when i'm hungry.",
       'stress, boredom',
       'I eat comfort food when im stressed out from school(finals week), when I`m sad, or when i am dealing with personal family issues.',
       'Boredom ', 'Stress, anger and sadness ',
       'sadness, stress, cold weather',
       'Sadness, boredom, late night snack ',
       'stress,  boredom, special occasions',
       'Friends, environment and boredom', 'boredom', 'Stress ',
       "I usually only eat comfort food when I'm bored, if i am doing something, i can go for hours without eating ",
       'Sadness, stress', 'boredom, sadness, hungry',
       'happiness, satisfaction', 'Mostly boredom',
       'sadness, depression ', 'Stress and boredom ',
       'A long day, not feeling well, winter ', 'Boredom, lazyniss ',
       'survival, bored', 'Boredom, anger, drun

In [28]:
df['cuisine'].unique()

array([nan,  1.,  3.,  2.,  6.,  4.,  5.])

In [29]:
mean_cu = df['cuisine'].mean() 
df['cuisine'] =  df['cuisine'].fillna(mean_cu)

In [30]:
df['cuisine'].unique()

array([1.38888889, 1.        , 3.        , 2.        , 6.        ,
       4.        , 5.        ])

In [31]:
df['exercise'].unique()

array([ 1.,  2.,  3., nan])

In [32]:
df[df['exercise']==' '].index.tolist()

[]

In [33]:
df.isnull().sum()

GPA                               0
Gender                            0
breakfast                         0
calories_chicken                  0
calories_day                      0
calories_scone                    0
coffee                            0
comfort_food                      0
comfort_food_reasons              2
comfort_food_reasons_coded       18
cook                              3
comfort_food_reasons_coded.1      0
cuisine                           0
diet_current                      1
diet_current_coded                0
drink                             2
eating_changes                    3
eating_changes_coded              0
eating_changes_coded1             0
eating_out                        0
employment                        9
ethnic_food                       0
exercise                         13
father_education                  1
father_profession                 2
fav_cuisine                       1
fav_cuisine_coded                 0
fav_food                    

In [34]:
numeric_columns =  df.select_dtypes(include=['number']).columns

In [35]:
df[numeric_columns].isnull().sum()

GPA                               0
Gender                            0
breakfast                         0
calories_chicken                  0
calories_day                      0
calories_scone                    0
coffee                            0
comfort_food_reasons_coded       18
cook                              3
comfort_food_reasons_coded.1      0
cuisine                           0
diet_current_coded                0
drink                             2
eating_changes_coded              0
eating_changes_coded1             0
eating_out                        0
employment                        9
ethnic_food                       0
exercise                         13
father_education                  1
fav_cuisine_coded                 0
fav_food                          2
fries                             0
fruit_day                         0
grade_level                       0
greek_food                        0
healthy_feeling                   0
ideal_diet_coded            

In [36]:
for column in numeric_columns:
 df[numeric_columns] = df[numeric_columns].fillna(df[numeric_columns].mean())

In [37]:
ob_columns = df.select_dtypes(include=['object']).columns

In [38]:
df[ob_columns].isnull().sum()

comfort_food             0
comfort_food_reasons     2
diet_current             1
eating_changes           3
father_profession        2
fav_cuisine              1
food_childhood           1
healthy_meal             1
ideal_diet               1
meals_dinner_friend      2
mother_profession        1
type_sports             25
weight                   2
dtype: int64

In [39]:
for column in numeric_columns:
 df[ob_columns] = df[ob_columns].fillna(df[ob_columns].mode())

In [40]:
df[ob_columns].isnull().sum()

comfort_food             0
comfort_food_reasons     2
diet_current             0
eating_changes           3
father_profession        2
fav_cuisine              1
food_childhood           1
healthy_meal             0
ideal_diet               0
meals_dinner_friend      2
mother_profession        1
type_sports             25
weight                   2
dtype: int64

In [41]:
df.head()

,GPA,Gender,breakfast,calories_chicken,calories_day,calories_scone,coffee,comfort_food,comfort_food_reasons,comfort_food_reasons_coded,...,sports,thai_food,tortilla_calories,turkey_calories,type_sports,veggies_day,vitamins,waffle_calories,weight,price
0,2.400,2,1,430,3.038095,315.0,1,none,we dont have comfort,9.0,...,1.0,1,1165.0,345,car racing,5,1,1315,187,NaN
1,3.654,1,1,610,3.000000,420.0,2,"chocolate, chips, ice cream","Stress, bored, anger",1.0,...,1.0,2,725.0,690,Basketball,4,2,900,155,NaN
2,3.300,1,1,720,4.000000,420.0,2,"frozen yogurt, pizza, fast food","stress, sadness",1.0,...,2.0,5,1165.0,500,none,5,1,900,I'm not answering this.,NaN
3,3.200,1,1,430,3.000000,420.0,2,"Pizza, Mac and cheese, ice cream",Boredom,2.0,...,2.0,5,725.0,690,NaN,3,1,1315,"Not sure, 240",NaN
4,3.500,1,1,720,2.000000,420.0,2,"Ice cream, chocolate, chips","Stress, boredom, cravings",1.0,...,1.0,4,940.0,500,Softball,4,2,760,190,NaN


In [42]:
df['comfort_food_reasons'].unique()

array(['we dont have comfort ', 'Stress, bored, anger', 'stress, sadness',
       'Boredom', 'Stress, boredom, cravings ',
       "None, i don't eat comfort food. I just eat when i'm hungry.",
       'stress, boredom',
       'I eat comfort food when im stressed out from school(finals week), when I`m sad, or when i am dealing with personal family issues.',
       'Boredom ', 'Stress, anger and sadness ',
       'sadness, stress, cold weather',
       'Sadness, boredom, late night snack ',
       'stress,  boredom, special occasions',
       'Friends, environment and boredom', 'boredom', 'Stress ',
       "I usually only eat comfort food when I'm bored, if i am doing something, i can go for hours without eating ",
       'Sadness, stress', 'boredom, sadness, hungry',
       'happiness, satisfaction', 'Mostly boredom',
       'sadness, depression ', 'Stress and boredom ',
       'A long day, not feeling well, winter ', 'Boredom, lazyniss ',
       'survival, bored', 'Boredom, anger, drun

In [43]:
df['exercise'].unique()

array([1.        , 2.        , 3.        , 1.58558559])

In [44]:
mean_ex = df['exercise'].mode() 
df['exercise'] =  df['exercise'].fillna(mean_ex)

In [45]:
df['exercise'].unique()

array([1.        , 2.        , 3.        , 1.58558559])

In [46]:
df['cook'].unique()

array([2.        , 3.        , 1.        , 5.        , 4.        ,
       2.79338843])

In [47]:
mean_cook = df['cook'].mean() 
df['cook'] =  df['cook'].fillna(mean_cook)

In [48]:
df['cook'].unique()

array([2.        , 3.        , 1.        , 5.        , 4.        ,
       2.79338843])

In [49]:
df['comfort_food_reasons_coded'].unique()

array([9.        , 1.        , 2.        , 4.        , 3.        ,
       7.        , 6.        , 5.        , 8.        , 2.69811321])

In [50]:
mean_reason = df['comfort_food_reasons_coded'].mean() 
df['comfort_food_reasons_coded'] =  df['comfort_food_reasons_coded'].fillna(mean_reason)

In [51]:
df['comfort_food_reasons_coded'].unique()

array([9.        , 1.        , 2.        , 4.        , 3.        ,
       7.        , 6.        , 5.        , 8.        , 2.69811321])

In [52]:
df['father_education'].unique()

array([5.        , 2.        , 4.        , 1.        , 3.        ,
       3.49593496])

In [53]:
mean_fe = df['father_education'].mean() 
df['father_education'] =  df['father_education'].fillna(mean_fe)

In [54]:
df['father_education'].unique()

array([5.        , 2.        , 4.        , 1.        , 3.        ,
       3.49593496])

In [55]:
df.isnull().sum()

GPA                               0
Gender                            0
breakfast                         0
calories_chicken                  0
calories_day                      0
calories_scone                    0
coffee                            0
comfort_food                      0
comfort_food_reasons              2
comfort_food_reasons_coded        0
cook                              0
comfort_food_reasons_coded.1      0
cuisine                           0
diet_current                      0
diet_current_coded                0
drink                             0
eating_changes                    3
eating_changes_coded              0
eating_changes_coded1             0
eating_out                        0
employment                        0
ethnic_food                       0
exercise                          0
father_education                  0
father_profession                 2
fav_cuisine                       1
fav_cuisine_coded                 0
fav_food                    

In [56]:
df['drink'].unique()

array([1.        , 2.        , 1.55737705])

In [57]:
mean_fe = df['drink'].mean() 
df['drink'] =  df['drink'].fillna(mean_fe)

In [58]:
df['drink'].unique()

array([1.        , 2.        , 1.55737705])

In [59]:
df['diet_current'].unique()

array(['eat good and exercise',
       "I eat about three times a day with some snacks. I try to eat healthy but it doesn't always work out that- sometimes eat fast food and mainly eat at Laker/ Egan ",
       'toast and fruit for breakfast, salad for lunch, usually grilled chicken and veggies (or some variation) for dinner',
       'College diet, cheap and easy foods most nights. Weekends traditionally, cook better homemade meals  ',
       'I try to eat healthy but often struggle because of living on campus. I still try to keep the choices I do make balanced with fruits and vegetables and limit the sweats. ',
       "My current diet is terrible. I barely have time to eat a meal in a day. When i do eat it's mostly not healthy.",
       'I eat a lot of chicken and broccoli for dinner, and usually tuna sandwiches for lunch.',
       'I eat a very healthy diet. Ocassionally, i will eat out and get unhealthy food.',
       'I eat whatever I want in moderation.',
       "I eat healthy all 

In [60]:
mean_dc = df['diet_current'].mode() 
df['diet_current'] =  df['diet_current'].fillna(mean_dc)

In [61]:
df['diet_current'].unique()

array(['eat good and exercise',
       "I eat about three times a day with some snacks. I try to eat healthy but it doesn't always work out that- sometimes eat fast food and mainly eat at Laker/ Egan ",
       'toast and fruit for breakfast, salad for lunch, usually grilled chicken and veggies (or some variation) for dinner',
       'College diet, cheap and easy foods most nights. Weekends traditionally, cook better homemade meals  ',
       'I try to eat healthy but often struggle because of living on campus. I still try to keep the choices I do make balanced with fruits and vegetables and limit the sweats. ',
       "My current diet is terrible. I barely have time to eat a meal in a day. When i do eat it's mostly not healthy.",
       'I eat a lot of chicken and broccoli for dinner, and usually tuna sandwiches for lunch.',
       'I eat a very healthy diet. Ocassionally, i will eat out and get unhealthy food.',
       'I eat whatever I want in moderation.',
       "I eat healthy all 

In [62]:
df.isnull().sum()

GPA                               0
Gender                            0
breakfast                         0
calories_chicken                  0
calories_day                      0
calories_scone                    0
coffee                            0
comfort_food                      0
comfort_food_reasons              2
comfort_food_reasons_coded        0
cook                              0
comfort_food_reasons_coded.1      0
cuisine                           0
diet_current                      0
diet_current_coded                0
drink                             0
eating_changes                    3
eating_changes_coded              0
eating_changes_coded1             0
eating_out                        0
employment                        0
ethnic_food                       0
exercise                          0
father_education                  0
father_profession                 2
fav_cuisine                       1
fav_cuisine_coded                 0
fav_food                    

In [63]:
df['comfort_food_reasons'].unique()

array(['we dont have comfort ', 'Stress, bored, anger', 'stress, sadness',
       'Boredom', 'Stress, boredom, cravings ',
       "None, i don't eat comfort food. I just eat when i'm hungry.",
       'stress, boredom',
       'I eat comfort food when im stressed out from school(finals week), when I`m sad, or when i am dealing with personal family issues.',
       'Boredom ', 'Stress, anger and sadness ',
       'sadness, stress, cold weather',
       'Sadness, boredom, late night snack ',
       'stress,  boredom, special occasions',
       'Friends, environment and boredom', 'boredom', 'Stress ',
       "I usually only eat comfort food when I'm bored, if i am doing something, i can go for hours without eating ",
       'Sadness, stress', 'boredom, sadness, hungry',
       'happiness, satisfaction', 'Mostly boredom',
       'sadness, depression ', 'Stress and boredom ',
       'A long day, not feeling well, winter ', 'Boredom, lazyniss ',
       'survival, bored', 'Boredom, anger, drun

In [64]:
mean_smfe = df['comfort_food_reasons'].mode() 
df['comfort_food_reasons'] =  df['comfort_food_reasons'].fillna(mean_smfe)

In [65]:
df['eating_changes'].unique()

array(['eat faster ', 'I eat out more than usual. ',
       'sometimes choosing to eat fast food instead of cooking simply for convenience',
       'Accepting cheap and premade/store bought foods',
       'I have eaten generally the same foods but I do find myself eating the same food frequently due to what I have found I like from egan and the laker. ',
       'Eating rice everyday. Eating less homemade food.',
       "I started eating a lot less and healthier because I wasn't playing sports year round anymore.",
       'Freshmen year i ate very unhealthy, but now it is much healthier because of self control.',
       'I snack less',
       "I cook a lot of my own foods back at home so not being able to cook my own healthy choices. I eat more carbs than normal when I'm at college due to the choices given in the cafe. ",
       'Nun ', 'Less meat. ',
       'I have been eating a lot more salads and soups.',
       'not as healthy because healthy food goes bad quickly and it is expensiv

In [66]:
mean_smfe = df['eating_changes'].mode() 
df['eating_changes'] =  df['eating_changes'].fillna(mean_smfe)

In [67]:
df['eating_changes'].unique()

array(['eat faster ', 'I eat out more than usual. ',
       'sometimes choosing to eat fast food instead of cooking simply for convenience',
       'Accepting cheap and premade/store bought foods',
       'I have eaten generally the same foods but I do find myself eating the same food frequently due to what I have found I like from egan and the laker. ',
       'Eating rice everyday. Eating less homemade food.',
       "I started eating a lot less and healthier because I wasn't playing sports year round anymore.",
       'Freshmen year i ate very unhealthy, but now it is much healthier because of self control.',
       'I snack less',
       "I cook a lot of my own foods back at home so not being able to cook my own healthy choices. I eat more carbs than normal when I'm at college due to the choices given in the cafe. ",
       'Nun ', 'Less meat. ',
       'I have been eating a lot more salads and soups.',
       'not as healthy because healthy food goes bad quickly and it is expensiv

In [68]:
df[ob_columns].isnull().sum()

comfort_food             0
comfort_food_reasons     2
diet_current             0
eating_changes           3
father_profession        2
fav_cuisine              1
food_childhood           1
healthy_meal             0
ideal_diet               0
meals_dinner_friend      2
mother_profession        1
type_sports             25
weight                   2
dtype: int64

In [69]:
df['comfort_food_reasons'].isnull()

0      False
1      False
2      False
3      False
4      False
5      False
6      False
7      False
8      False
9      False
10     False
11     False
12     False
13     False
14     False
15     False
16     False
17     False
18     False
19     False
20     False
21     False
22     False
23     False
24     False
25     False
26     False
27     False
28     False
29     False
30     False
31     False
32     False
33     False
34     False
35     False
36     False
37     False
38     False
39     False
40     False
41     False
42     False
43     False
44     False
45     False
46     False
47     False
48     False
49     False
50     False
51     False
52     False
53     False
54     False
55     False
56     False
57     False
58     False
59     False
60     False
61     False
62     False
63     False
64     False
65     False
66     False
67     False
68     False
69     False
70     False
71     False
72     False
73     False
74      True
75     False
76     False

In [70]:
mode_value = df["comfort_food_reasons"].mode()[0]

df.loc[[74, 88], "comfort_food_reasons"] = mode_value

In [71]:
df[ob_columns].isnull().sum()

comfort_food             0
comfort_food_reasons     0
diet_current             0
eating_changes           3
father_profession        2
fav_cuisine              1
food_childhood           1
healthy_meal             0
ideal_diet               0
meals_dinner_friend      2
mother_profession        1
type_sports             25
weight                   2
dtype: int64

In [72]:
df['eating_changes'].isnull()

0      False
1      False
2      False
3      False
4      False
5      False
6      False
7      False
8      False
9      False
10     False
11     False
12     False
13     False
14     False
15     False
16     False
17     False
18     False
19     False
20     False
21     False
22     False
23     False
24     False
25     False
26     False
27     False
28     False
29     False
30     False
31     False
32     False
33     False
34     False
35     False
36     False
37     False
38     False
39     False
40     False
41     False
42     False
43     False
44     False
45     False
46     False
47     False
48     False
49     False
50     False
51     False
52     False
53      True
54     False
55     False
56     False
57     False
58     False
59     False
60     False
61     False
62     False
63      True
64     False
65     False
66     False
67     False
68     False
69     False
70     False
71     False
72     False
73     False
74      True
75     False
76     False

In [73]:
mode_value = df["eating_changes"].mode()[0]

df.loc[[74, 53, 63], "eating_changes"] = mode_value

In [74]:
df['father_profession'].isnull()

0      False
1      False
2      False
3      False
4      False
5      False
6      False
7      False
8      False
9      False
10     False
11     False
12     False
13     False
14     False
15     False
16     False
17     False
18     False
19     False
20     False
21     False
22     False
23     False
24     False
25     False
26     False
27     False
28     False
29     False
30      True
31     False
32     False
33     False
34     False
35     False
36     False
37     False
38     False
39     False
40     False
41     False
42     False
43     False
44     False
45     False
46     False
47     False
48     False
49     False
50     False
51     False
52     False
53     False
54     False
55     False
56     False
57     False
58     False
59     False
60     False
61     False
62     False
63     False
64     False
65     False
66     False
67     False
68     False
69     False
70     False
71     False
72     False
73     False
74     False
75     False
76     False

In [76]:
df['fav_cuisine'].isnull().sum()

np.int64(1)

In [78]:
df['food_childhood'].isnull()

0      False
1      False
2      False
3      False
4      False
5      False
6      False
7      False
8      False
9      False
10     False
11     False
12     False
13     False
14     False
15     False
16     False
17     False
18     False
19     False
20     False
21     False
22     False
23     False
24     False
25     False
26     False
27     False
28     False
29     False
30     False
31     False
32     False
33     False
34     False
35     False
36     False
37     False
38     False
39     False
40     False
41     False
42     False
43     False
44     False
45     False
46     False
47     False
48     False
49     False
50     False
51     False
52     False
53     False
54     False
55     False
56     False
57     False
58     False
59     False
60     False
61     False
62     False
63     False
64     False
65     False
66     False
67     False
68     False
69     False
70     False
71     False
72     False
73     False
74      True
75     False
76     False

In [80]:
df['meals_dinner_friend'].isnull()

0      False
1      False
2      False
3      False
4      False
5      False
6      False
7      False
8      False
9      False
10     False
11     False
12     False
13     False
14     False
15     False
16     False
17     False
18     False
19     False
20     False
21     False
22     False
23     False
24     False
25     False
26     False
27     False
28     False
29     False
30     False
31     False
32     False
33     False
34     False
35     False
36     False
37     False
38     False
39     False
40     False
41     False
42     False
43     False
44     False
45     False
46     False
47     False
48     False
49     False
50     False
51     False
52     False
53     False
54     False
55     False
56     False
57     False
58     False
59     False
60     False
61     False
62     False
63     False
64     False
65     False
66     False
67     False
68     False
69     False
70     False
71     False
72     False
73     False
74     False
75     False
76     False

In [81]:
mode_value = df["meals_dinner_friend"].mode()[0]

df.loc[[101], "meals_dinner_friend"] = mode_value

In [82]:
df['mother_profession'].isnull().sum()

np.int64(1)

In [83]:
df[ob_columns].isnull().sum()

comfort_food             0
comfort_food_reasons     0
diet_current             0
eating_changes           0
father_profession        2
fav_cuisine              1
food_childhood           0
healthy_meal             0
ideal_diet               0
meals_dinner_friend      1
mother_profession        1
type_sports             25
weight                   2
dtype: int64

In [ ]:
df['type_sports'].isnull()

In [84]:
mode_typ_sp= df['type_sports'].mode() 
df['type_sports'] =  df['type_sports'].fillna(mode_typ_sp)

In [85]:
null_locs = df[df['type_sports'].isnull()].index
print(null_locs)

Index([  3,  16,  28,  29,  33,  41,  42,  50,  53,  61,  65,  69,  72,  74,
        80,  88,  93, 101, 102, 106, 112, 113, 118, 123, 124],
      dtype='int64')


In [86]:
mode_value = df["type_sports"].mode()[0]

df.loc[[  3,  16,  28,  29,  33,  41,  42,  50,  53,  61,  65,  69,  72,  80,
        88,  93, 101, 102, 106, 112, 113, 118, 123, 124], "type_sports"] = mode_value

In [87]:
df[ob_columns].isnull().sum()

comfort_food            0
comfort_food_reasons    0
diet_current            0
eating_changes          0
father_profession       2
fav_cuisine             1
food_childhood          0
healthy_meal            0
ideal_diet              0
meals_dinner_friend     1
mother_profession       1
type_sports             1
weight                  2
dtype: int64

In [88]:
df['meals_dinner_friend'].isnull()

0      False
1      False
2      False
3      False
4      False
5      False
6      False
7      False
8      False
9      False
10     False
11     False
12     False
13     False
14     False
15     False
16     False
17     False
18     False
19     False
20     False
21     False
22     False
23     False
24     False
25     False
26     False
27     False
28     False
29     False
30     False
31     False
32     False
33     False
34     False
35     False
36     False
37     False
38     False
39     False
40     False
41     False
42     False
43     False
44     False
45     False
46     False
47     False
48     False
49     False
50     False
51     False
52     False
53     False
54     False
55     False
56     False
57     False
58     False
59     False
60     False
61     False
62     False
63     False
64     False
65     False
66     False
67     False
68     False
69     False
70     False
71     False
72     False
73     False
74     False
75     False
76     False

In [89]:
mode_value = df["meals_dinner_friend"].mode()[0]

df.loc[[102], "meals_dinner_friend"] = mode_value

In [90]:
df['weight'].isnull()

0      False
1      False
2      False
3      False
4      False
5      False
6      False
7      False
8      False
9      False
10     False
11     False
12     False
13     False
14     False
15     False
16     False
17     False
18     False
19     False
20     False
21     False
22     False
23     False
24     False
25     False
26     False
27     False
28     False
29     False
30     False
31     False
32      True
33     False
34     False
35     False
36     False
37     False
38     False
39     False
40     False
41     False
42     False
43     False
44     False
45     False
46     False
47     False
48     False
49     False
50     False
51     False
52     False
53     False
54     False
55     False
56     False
57     False
58     False
59     False
60     False
61     False
62     False
63     False
64     False
65     False
66     False
67     False
68     False
69     False
70     False
71     False
72     False
73     False
74      True
75     False
76     False

In [91]:
mode_value = df["weight"].mode()[0]

df.loc[[32], "weight"] = mode_value

In [92]:
df[ob_columns].isnull().sum()

comfort_food            0
comfort_food_reasons    0
diet_current            0
eating_changes          0
father_profession       2
fav_cuisine             1
food_childhood          0
healthy_meal            0
ideal_diet              0
meals_dinner_friend     0
mother_profession       1
type_sports             1
weight                  1
dtype: int64

In [93]:
df.isnull().sum()

GPA                               0
Gender                            0
breakfast                         0
calories_chicken                  0
calories_day                      0
calories_scone                    0
coffee                            0
comfort_food                      0
comfort_food_reasons              0
comfort_food_reasons_coded        0
cook                              0
comfort_food_reasons_coded.1      0
cuisine                           0
diet_current                      0
diet_current_coded                0
drink                             0
eating_changes                    0
eating_changes_coded              0
eating_changes_coded1             0
eating_out                        0
employment                        0
ethnic_food                       0
exercise                          0
father_education                  0
father_profession                 2
fav_cuisine                       1
fav_cuisine_coded                 0
fav_food                    

In [94]:
df.head(25)

,GPA,Gender,breakfast,calories_chicken,calories_day,calories_scone,coffee,comfort_food,comfort_food_reasons,comfort_food_reasons_coded,...,sports,thai_food,tortilla_calories,turkey_calories,type_sports,veggies_day,vitamins,waffle_calories,weight,price
0,2.400000,2,1,430,3.038095,315.0,1,none,we dont have comfort,9.0,...,1.000000,1,1165.0,345,car racing,5,1,1315,187,NaN
1,3.654000,1,1,610,3.000000,420.0,2,"chocolate, chips, ice cream","Stress, bored, anger",1.0,...,1.000000,2,725.0,690,Basketball,4,2,900,155,NaN
2,3.300000,1,1,720,4.000000,420.0,2,"frozen yogurt, pizza, fast food","stress, sadness",1.0,...,2.000000,5,1165.0,500,none,5,1,900,I'm not answering this.,NaN
3,3.200000,1,1,430,3.000000,420.0,2,"Pizza, Mac and cheese, ice cream",Boredom,2.0,...,2.000000,5,725.0,690,none,3,1,1315,"Not sure, 240",NaN
4,3.500000,1,1,720,2.000000,420.0,2,"Ice cream, chocolate, chips","Stress, boredom, cravings",1.0,...,1.000000,4,940.0,500,Softball,4,2,760,190,NaN
5,2.250000,1,1,610,3.000000,980.0,2,"Candy, brownies and soda.","None, i don't eat comfort food. I just eat whe...",4.0,...,2.000000,4,940.0,345,None.,1,2,1315,190,NaN
6,3.800000,2,1,610,3.000000,420.0,2,"Chocolate, ice cream, french fries, pretzels","stress, boredom",1.0,...,1.000000,5,940.0,690,soccer,4,1,1315,180,NaN
7,3.300000,1,1,720,3.000000,420.0,1,"Ice cream, cheeseburgers, chips.",I eat comfort food when im stressed out from s...,1.0,...,2.000000,1,725.0,500,none,4,2,1315,137,NaN
8,3.300000,1,1,430,3.038095,420.0,1,"Donuts, ice cream, chips",Boredom,2.0,...,2.000000,5,725.0,345,none,3,2,760,180,NaN
9,3.300000,1,1,430,3.000000,315.0,2,"Mac and cheese, chocolate, and pasta","Stress, anger and sadness",1.0,...,1.000000,4,580.0,345,field hockey,5,1,900,125,NaN


In [95]:
df['Gender'] = df['Gender'].replace({2: 'female', 1: 'male'})

In [96]:
df.head()

,GPA,Gender,breakfast,calories_chicken,calories_day,calories_scone,coffee,comfort_food,comfort_food_reasons,comfort_food_reasons_coded,...,sports,thai_food,tortilla_calories,turkey_calories,type_sports,veggies_day,vitamins,waffle_calories,weight,price
0,2.400,female,1,430,3.038095,315.0,1,none,we dont have comfort,9.0,...,1.0,1,1165.0,345,car racing,5,1,1315,187,NaN
1,3.654,male,1,610,3.000000,420.0,2,"chocolate, chips, ice cream","Stress, bored, anger",1.0,...,1.0,2,725.0,690,Basketball,4,2,900,155,NaN
2,3.300,male,1,720,4.000000,420.0,2,"frozen yogurt, pizza, fast food","stress, sadness",1.0,...,2.0,5,1165.0,500,none,5,1,900,I'm not answering this.,NaN
3,3.200,male,1,430,3.000000,420.0,2,"Pizza, Mac and cheese, ice cream",Boredom,2.0,...,2.0,5,725.0,690,none,3,1,1315,"Not sure, 240",NaN
4,3.500,male,1,720,2.000000,420.0,2,"Ice cream, chocolate, chips","Stress, boredom, cravings",1.0,...,1.0,4,940.0,500,Softball,4,2,760,190,NaN


In [101]:
df['sports'] = df['sports'].replace({'Yes': 'Active', 'No': 'Not-Active'})

In [102]:
df.head()

,GPA,Gender,breakfast,calories_chicken,calories_day,calories_scone,coffee,comfort_food,comfort_food_reasons,comfort_food_reasons_coded,...,sports,thai_food,tortilla_calories,turkey_calories,type_sports,veggies_day,vitamins,waffle_calories,weight,price
0,2.400,female,1,430,3.038095,315.0,1,none,we dont have comfort,9.0,...,Active,1,1165.0,345,car racing,5,1,1315,187,NaN
1,3.654,male,1,610,3.000000,420.0,2,"chocolate, chips, ice cream","Stress, bored, anger",1.0,...,Active,2,725.0,690,Basketball,4,2,900,155,NaN
2,3.300,male,1,720,4.000000,420.0,2,"frozen yogurt, pizza, fast food","stress, sadness",1.0,...,Not-Active,5,1165.0,500,none,5,1,900,I'm not answering this.,NaN
3,3.200,male,1,430,3.000000,420.0,2,"Pizza, Mac and cheese, ice cream",Boredom,2.0,...,Not-Active,5,725.0,690,none,3,1,1315,"Not sure, 240",NaN
4,3.500,male,1,720,2.000000,420.0,2,"Ice cream, chocolate, chips","Stress, boredom, cravings",1.0,...,Active,4,940.0,500,Softball,4,2,760,190,NaN


### Using replace(): the numerical data type column

In [103]:
df['breakfast'] = df['breakfast'].astype(str).replace({'1' : 'Yes', '2' : 'No'})

In [104]:
df['coffee'] = df['coffee'].astype(str).replace({'1' : 'Yes', '2' : 'No'})

AttributeError: 'DataFrame' object has no attribute 'col'